- name: "Auto-X"
  display_name: Auto-X (Gauge)

- name: "sam2_hiera_tiny_20240803"
  display_name: Segment Anything 2 (Hiera-Tiny)
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_tiny.zip
- name: "sam2_hiera_small_20240803"
  display_name: Segment Anything 2 (Hiera-Small)
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_small.zip
- name: "sam2_hiera_base_plus_20240803"
  display_name: Segment Anything 2 (Hiera-Base+)
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_base_plus.zip
- name: "sam2_hiera_large_20240803"
  display_name: Segment Anything 2 (Hiera-Large)
  download_url: https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_large.zip